version: '3'

services:
  db:
    image: mysql:5.7
    user: '1000:1000'
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=ceramic
    - MYSQL_PASSWORD=secret
    - MYSQL_DATABASE=ceramic
    volumes:
    - ./db:/var/lib/mysql

  fpm:
    build: vm
    entrypoint: ["bash", "-c", "service php7.3-fpm start && exec tail -fn0 /var/log/php*"]
    user: root
    depends_on:
    - db
    volumes:
    - ./www:/app
    - ./builder:/builder
    - ./home:/home

  builder:
    build: vm
    entrypoint: ["php", "/app/artisan", "build-one"]
    user: noob
    depends_on:
    - db
    restart: unless-stopped
    volumes:
    - ./www:/app
    - ./builder:/builder
    - ./home:/home

  nginx:
    build: nginx
    entrypoint: ["bash", "-c", "nginx && exec tail -fn0 /var/log/nginx/*.log"]
    volumes:
    - ./www:/app:ro
    - ./nginx/nginx-default:/etc/nginx/sites-available/default:ro
    ports:
    - '127.0.0.1:7001:80'

  adminer:
    image: adminer
    depends_on:
    - db
    ports:
    - '127.0.0.1:7002:8080'
